### ISSUE TITLE
Missing Tests

### ISSUE THREAD

**Issue by 5tigerjelly** [5tigerjelly/search-suggestion-python#1]

**Comment by sofignatova** [comment]
Hi, would you mind if I tried to add the tests? I'm new to Python testing so I might need some help.

**Comment by 5tigerjelly** [comment]
@sofignatova Hello 👋 
It would be great if you can add some tests! I can help you along the way as well. To contribute please fork this repo to your account and clone it to your machine. This is a [page](https://github.com/pallets/flask/blob/master/CONTRIBUTING.rst#submitting-patches) from flask, but the process is about the same for any repo.

Here are some resources to get you started on adding tests as well - https://realpython.com/python-testing/

**Comment by sofignatova** [comment]
Thanks, I'm working on this now!
